package validate

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/RamazanKara/openexit/internal/inventory"
)

func addEdgeCandidateChecks(projectDir string, inv *inventory.Inventory, add func(string, string, string, bool)) {
	if inv == nil || inv.Source.Type != "edge" {
		return
	}
	var problems []string
	problems = append(problems, validateEdgeVCLCandidate(projectDir, inv)...)
	problems = append(problems, validateEdgeHAProxyCandidate(projectDir, inv)...)
	problems = append(problems, validateEdgeCorazaCandidate(projectDir, inv)...)
	if len(problems) > 0 {
		sort.Strings(problems)
		add("edge-candidates", "failed", strings.Join(problems, "; "), true)
		return
	}
	add("edge-candidates", "passed", "", true)
}

func validateEdgeVCLCandidate(projectDir string, inv *inventory.Inventory) []string {
	path := filepath.Join(projectDir, "generated-config", "edge", "varnish", "default.candidate.vcl")
	data, err := os.ReadFile(path)
	if err != nil {
		return []string{"generated-config/edge/varnish/default.candidate.vcl: " + err.Error()}
	}
	text := string(data)
	var problems []string
	problems = append(problems, validateEdgeTextSafety("generated-config/edge/varnish/default.candidate.vcl", text, "Candidate VCL generated by OpenExit", "Review before use")...)
	for _, required := range []string{"vcl 4.1;", "sub vcl_recv", "sub vcl_backend_response"} {
		if !strings.Contains(text, required) {
			problems = append(problems, fmt.Sprintf("VCL candidate missing %q", required))
		}
	}
	for i, origin := range inv.Assets.Origins {
		name := "origin_" + edgeConfigIdentifier(origin.ID)
		if i == 0 {
			name = "default"
		}
		for _, required := range []string{
			"# origin " + edgeSanitizeConfigValue(origin.ID) + " evidence=" + origin.EvidenceRef,
			"backend " + name,
			fmt.Sprintf(".host = %q", origin.Hostname),
			fmt.Sprintf(".port = %q", fmt.Sprintf("%d", origin.Port)),
		} {
			if !strings.Contains(text, required) {
				problems = append(problems, fmt.Sprintf("VCL candidate missing origin %s marker %q", origin.ID, required))
			}
		}
	}
	for _, rule := range inv.Assets.CacheRules {
		if !strings.Contains(text, "# cache-rule "+edgeSanitizeConfigValue(rule.ID)+" evidence="+rule.EvidenceRef) {
			problems = append(problems, fmt.Sprintf("VCL candidate missing cache rule evidence for %s", rule.ID))
		}
		pattern := edgeVCLRegex(rule.Pattern)
		switch {
		case strings.EqualFold(rule.Action, "bypass"):
			if !strings.Contains(text, fmt.Sprintf("if (req.url ~ %q) { return (pass); }", pattern)) {
				problems = append(problems, fmt.Sprintf("VCL candidate missing bypass rule for %s", rule.ID))
			}
		case strings.EqualFold(rule.Action, "cache"):
			if !strings.Contains(text, fmt.Sprintf("if (req.url ~ %q) { unset req.http.Cookie; }", pattern)) {
				problems = append(problems, fmt.Sprintf("VCL candidate missing cache cookie handling for %s", rule.ID))
			}
			if rule.EdgeTTL > 0 && !strings.Contains(text, fmt.Sprintf("if (bereq.url ~ %q) { set beresp.ttl = %ds; }", pattern, rule.EdgeTTL)) {
				problems = append(problems, fmt.Sprintf("VCL candidate missing edge TTL for %s", rule.ID))
			}
		}
	}
	for _, rule := range inv.Assets.PageRules {
		if !rule.Enabled || !containsString(rule.Actions, "cache_everything") {
			continue
		}
		if !strings.Contains(text, "# page-rule "+edgeSanitizeConfigValue(rule.ID)+" evidence="+rule.EvidenceRef) {
			problems = append(problems, fmt.Sprintf("VCL candidate missing page rule evidence for %s", rule.ID))
		}
		if !strings.Contains(text, fmt.Sprintf("if (req.http.host + req.url ~ %q) { unset req.http.Cookie; }", edgeVCLRegex(rule.Target))) {
			problems = append(problems, fmt.Sprintf("VCL candidate missing cache-everything page rule for %s", rule.ID))
		}
	}
	problems = append(problems, validateEdgeREADME(projectDir, "varnish", []string{"Candidate VCL", "cache and page-rule metadata", "Review cache keys", "origin behavior"})...)
	return problems
}

func validateEdgeHAProxyCandidate(projectDir string, inv *inventory.Inventory) []string {
	path := filepath.Join(projectDir, "generated-config", "edge", "haproxy", "haproxy.candidate.cfg")
	data, err := os.ReadFile(path)
	if err != nil {
		return []string{"generated-config/edge/haproxy/haproxy.candidate.cfg: " + err.Error()}
	}
	text := string(data)
	var problems []string
	problems = append(problems, validateEdgeTextSafety("generated-config/edge/haproxy/haproxy.candidate.cfg", text, "Candidate HAProxy config generated by OpenExit", "Review before use")...)
	for _, required := range []string{"global", "defaults", "frontend edge_https", "bind *:443 ssl crt /etc/haproxy/certs/site.pem"} {
		if !strings.Contains(text, required) {
			problems = append(problems, fmt.Sprintf("HAProxy candidate missing %q", required))
		}
	}
	for _, redirect := range inv.Assets.Redirects {
		for _, required := range []string{
			"# " + edgeSanitizeConfigValue(redirect.Name) + " evidence=" + redirect.EvidenceRef,
			fmt.Sprintf("http-request redirect code %d location %s if { hdr(host) -m str %s }", redirect.StatusCode, edgeSanitizeConfigValue(redirect.Target), edgeRedirectHost(redirect.Source)),
		} {
			if !strings.Contains(text, required) {
				problems = append(problems, fmt.Sprintf("HAProxy candidate missing redirect %s marker %q", redirect.ID, required))
			}
		}
	}
	for i, origin := range inv.Assets.Origins {
		name := edgeConfigIdentifier(origin.ID)
		if i == 0 && !strings.Contains(text, "default_backend be_"+name) {
			problems = append(problems, fmt.Sprintf("HAProxy candidate missing default backend for origin %s", origin.ID))
		}
		for _, required := range []string{
			"# origin " + edgeSanitizeConfigValue(origin.ID) + " evidence=" + origin.EvidenceRef,
			fmt.Sprintf("acl host_%s hdr(host) -i %s", name, edgeSanitizeConfigValue(origin.HostHeader)),
			fmt.Sprintf("use_backend be_%s if host_%s", name, name),
			"backend be_" + name,
			fmt.Sprintf("server %s %s:%d", name, edgeSanitizeConfigValue(origin.Hostname), origin.Port),
		} {
			if !strings.Contains(text, required) {
				problems = append(problems, fmt.Sprintf("HAProxy candidate missing origin %s marker %q", origin.ID, required))
			}
		}
		if strings.EqualFold(origin.Scheme, "https") {
			verify := "required"
			if !origin.TLSVerify {
				verify = "none"
			}
			if !strings.Contains(text, "ssl verify "+verify+" sni str("+edgeSanitizeConfigValue(origin.Hostname)+")") {
				problems = append(problems, fmt.Sprintf("HAProxy candidate missing TLS verify %s for origin %s", verify, origin.ID))
			}
		}
		if origin.HealthCheck && !strings.Contains(text, fmt.Sprintf("server %s %s:%d", name, edgeSanitizeConfigValue(origin.Hostname), origin.Port)+" check") {
			problems = append(problems, fmt.Sprintf("HAProxy candidate missing health check for origin %s", origin.ID))
		}
	}
	problems = append(problems, validateEdgeREADME(projectDir, "haproxy", []string{"Candidate HAProxy", "redirect", "origin definitions", "Review certificates", "health checks"})...)
	return problems
}

func validateEdgeCorazaCandidate(projectDir string, inv *inventory.Inventory) []string {
	path := filepath.Join(projectDir, "generated-config", "edge", "coraza", "coraza-rules.candidate.conf")
	data, err := os.ReadFile(path)
	if err != nil {
		return []string{"generated-config/edge/coraza/coraza-rules.candidate.conf: " + err.Error()}
	}
	text := string(data)
	var problems []string
	problems = append(problems, validateEdgeTextSafety("generated-config/edge/coraza/coraza-rules.candidate.conf", text, "Candidate Coraza rules generated by OpenExit", "Review before use")...)
	if !strings.Contains(text, "SecRuleEngine On") {
		problems = append(problems, "Coraza candidate missing SecRuleEngine On")
	}
	for _, rule := range inv.Assets.WAFRules {
		action := edgeCorazaAction(rule.Action, rule.Enabled, false)
		for _, required := range []string{
			"# waf-rule " + edgeSanitizeConfigValue(rule.ID) + " evidence=" + rule.EvidenceRef,
			"@contains " + edgeCorazaMatchValue(rule.Expression),
			action,
			"msg:'" + edgeSanitizeConfigValue(rule.Name) + "'",
		} {
			if !strings.Contains(text, required) {
				problems = append(problems, fmt.Sprintf("Coraza candidate missing WAF rule %s marker %q", rule.ID, required))
			}
		}
	}
	for _, rule := range inv.Assets.BotRules {
		action := edgeCorazaAction(rule.Action, rule.Enabled, true)
		for _, required := range []string{
			"# bot-rule " + edgeSanitizeConfigValue(rule.ID) + " evidence=" + rule.EvidenceRef,
			"REQUEST_HEADERS:User-Agent",
			action,
			"msg:'" + edgeSanitizeConfigValue(rule.Name) + "'",
		} {
			if !strings.Contains(text, required) {
				problems = append(problems, fmt.Sprintf("Coraza candidate missing bot rule %s marker %q", rule.ID, required))
			}
		}
	}
	problems = append(problems, validateEdgeREADME(projectDir, "coraza", []string{"Candidate Coraza rules", "conservative placeholders", "WAF and bot metadata", "OWASP CRS"})...)
	return problems
}

func validateEdgeTextSafety(name, text string, required ...string) []string {
	var problems []string
	for _, marker := range required {
		if !strings.Contains(text, marker) {
			problems = append(problems, fmt.Sprintf("%s missing safety marker %q", name, marker))
		}
	}
	if inventory.ContainsSecret(text) {
		problems = append(problems, name+" contains secret-like content")
	}
	return problems
}

func validateEdgeREADME(projectDir, dir string, required []string) []string {
	path := filepath.Join(projectDir, "generated-config", "edge", dir, "README.md")
	data, err := os.ReadFile(path)
	if err != nil {
		return []string{fmt.Sprintf("generated-config/edge/%s/README.md: %v", dir, err)}
	}
	readme := string(data)
	for _, marker := range required {
		if !strings.Contains(readme, marker) {
			return []string{fmt.Sprintf("generated-config/edge/%s/README.md: missing %q", dir, marker)}
		}
	}
	return nil
}

func edgeVCLRegex(pattern string) string {
	pattern = strings.TrimSpace(pattern)
	pattern = strings.TrimPrefix(pattern, "https://")
	pattern = strings.TrimPrefix(pattern, "http://")
	pattern = strings.ReplaceAll(pattern, ".", "\\.")
	pattern = strings.ReplaceAll(pattern, "*", ".*")
	return pattern
}

func edgeRedirectHost(source string) string {
	source = strings.TrimPrefix(source, "https://")
	source = strings.TrimPrefix(source, "http://")
	host, _, _ := strings.Cut(source, "/")
	return edgeSanitizeConfigValue(strings.TrimSuffix(host, "*"))
}

func edgeCorazaMatchValue(expression string) string {
	if _, after, ok := strings.Cut(expression, "contains"); ok {
		return strings.Trim(strings.TrimSpace(after), "\"'")
	}
	return "/"
}

func edgeCorazaAction(action string, enabled bool, bot bool) string {
	if !enabled {
		return "pass,nolog"
	}
	if edgeObserveOnlyAction(action) || (bot && strings.Contains(strings.ToLower(action), "challenge")) {
		return "pass,log"
	}
	return "deny,status:403"
}

func edgeSanitizeConfigValue(value string) string {
	value = strings.ReplaceAll(value, "\n", " ")
	value = strings.ReplaceAll(value, "\r", " ")
	value = strings.ReplaceAll(value, "'", "")
	value = strings.ReplaceAll(value, "\"", "")
	return strings.TrimSpace(value)
}

func edgeConfigIdentifier(value string) string {
	return strings.ReplaceAll(inventory.Slug(value), "-", "_")
}

func edgeObserveOnlyAction(action string) bool {
	action = strings.ToLower(strings.TrimSpace(action))
	return action == "log" || action == "count" || action == "simulate"
}
