package export

import (
	"archive/zip"
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/RamazanKara/openexit/internal/validate"
	"github.com/RamazanKara/openexit/internal/version"
	"gopkg.in/yaml.v3"
)

type Options struct {
	ProjectDir string
	Format     string
	Out        string
	Force      bool
}

func Bundle(opts Options) error {
	if opts.Format == "" {
		opts.Format = "zip"
	}
	if opts.Format != "zip" {
		return fmt.Errorf("unsupported export format %q", opts.Format)
	}
	if opts.Out == "" {
		return fmt.Errorf("--out is required")
	}
	report, err := validate.Run(opts.ProjectDir, false)
	if err != nil && !opts.Force {
		return fmt.Errorf("refusing export because validation status is %s; rerun with --force to override", reportStatus(report))
	}
	files, err := bundleFiles(opts.ProjectDir)
	if err != nil {
		return err
	}
	return writeZip(opts.ProjectDir, opts.Out, files, report)
}

type BundleManifest struct {
	APIVersion  string               `json:"apiVersion"`
	Kind        string               `json:"kind"`
	GeneratedAt string               `json:"generatedAt"`
	Build       BundleBuild          `json:"build"`
	Project     BundleProject        `json:"project"`
	Validation  BundleValidation     `json:"validation"`
	Files       []BundleManifestFile `json:"files"`
}

type BundleBuild struct {
	Version string `json:"version"`
	Commit  string `json:"commit"`
	Date    string `json:"date"`
}

type BundleProject struct {
	Name   string `json:"name"`
	Source string `json:"source,omitempty"`
	Target string `json:"target,omitempty"`
}

type BundleValidation struct {
	Status   string `json:"status"`
	Checks   int    `json:"checks"`
	Passed   int    `json:"passed"`
	Failed   int    `json:"failed"`
	Warnings int    `json:"warnings"`
}

type BundleManifestFile struct {
	Path   string `json:"path"`
	Size   int64  `json:"size"`
	SHA256 string `json:"sha256"`
}

func bundleFiles(projectDir string) ([]string, error) {
	include := map[string]bool{
		"openexit.yaml":    true,
		"inventory":        true,
		"assessment":       true,
		"mapping":          true,
		"generated-config": true,
		"validation":       true,
		"evidence":         true,
	}
	var files []string
	err := filepath.WalkDir(projectDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(projectDir, path)
		if err != nil || rel == "." {
			return err
		}
		if d.Type()&os.ModeSymlink != 0 {
			return fmt.Errorf("refusing to export symlink %s", rel)
		}
		top := strings.Split(filepath.ToSlash(rel), "/")[0]
		if !include[top] {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		if d.IsDir() {
			return nil
		}
		files = append(files, path)
		return nil
	})
	sort.Strings(files)
	return files, err
}

func writeZip(projectDir, out string, files []string, report *validate.Report) (err error) {
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil && filepath.Dir(out) != "." {
		return err
	}
	f, err := os.Create(out)
	if err != nil {
		return err
	}
	defer func() {
		if closeErr := f.Close(); err == nil {
			err = closeErr
		}
	}()
	zw := zip.NewWriter(f)
	defer func() {
		if closeErr := zw.Close(); err == nil {
			err = closeErr
		}
	}()
	checksums := map[string]string{}
	var manifestFiles []BundleManifestFile
	prefix := "openexit-evidence"
	fixedTime := time.Date(2026, 5, 24, 0, 0, 0, 0, time.UTC)
	generatedAt := time.Now().UTC().Format(time.RFC3339)
	for _, path := range files {
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(projectDir, path)
		name := prefix + "/" + filepath.ToSlash(rel)
		if err := addZipFile(zw, name, fixedTime, data); err != nil {
			return err
		}
		sum := sha256.Sum256(data)
		digest := hex.EncodeToString(sum[:])
		relName := filepath.ToSlash(rel)
		checksums[relName] = digest
		manifestFiles = append(manifestFiles, BundleManifestFile{
			Path:   relName,
			Size:   int64(len(data)),
			SHA256: digest,
		})
	}

	manifestData, err := json.MarshalIndent(buildManifest(projectDir, generatedAt, report, manifestFiles), "", "  ")
	if err != nil {
		return err
	}
	manifestData = append(manifestData, '\n')
	if err := addSyntheticZipFile(zw, prefix, "manifest.json", fixedTime, manifestData, checksums); err != nil {
		return err
	}

	readme := fmt.Sprintf(`# OpenExit Evidence Bundle

Generated by OpenExit.

- Version: %s
- Commit: %s
- Build date: %s
- Bundle generated at: %s

This bundle contains local inventory, assessment, generated candidates, validation, and redacted evidence. Candidate configs are not production-ready until reviewed.
The machine-readable bundle manifest is available at manifest.json.
`, version.Version, version.Commit, version.Date, generatedAt)
	if err := addSyntheticZipFile(zw, prefix, "README.md", fixedTime, []byte(readme), checksums); err != nil {
		return err
	}

	var checks bytes.Buffer
	keys := make([]string, 0, len(checksums))
	for path := range checksums {
		keys = append(keys, path)
	}
	sort.Strings(keys)
	for _, path := range keys {
		_, _ = fmt.Fprintf(&checks, "%s  %s\n", checksums[path], path)
	}
	return addZipFile(zw, prefix+"/checksums.txt", fixedTime, checks.Bytes())
}

func buildManifest(projectDir, generatedAt string, report *validate.Report, files []BundleManifestFile) BundleManifest {
	return BundleManifest{
		APIVersion:  "openexit.dev/v1alpha1",
		Kind:        "EvidenceBundle",
		GeneratedAt: generatedAt,
		Build: BundleBuild{
			Version: version.Version,
			Commit:  version.Commit,
			Date:    version.Date,
		},
		Project:    readBundleProject(projectDir),
		Validation: validationSummary(report),
		Files:      files,
	}
}

func readBundleProject(projectDir string) BundleProject {
	project := BundleProject{Name: filepath.Base(projectDir)}
	data, err := os.ReadFile(filepath.Join(projectDir, "openexit.yaml"))
	if err != nil {
		return project
	}
	var manifest struct {
		Metadata struct {
			Name string `yaml:"name"`
		} `yaml:"metadata"`
		Source struct {
			Type string `yaml:"type"`
		} `yaml:"source"`
		Target struct {
			Type string `yaml:"type"`
		} `yaml:"target"`
	}
	if err := yaml.Unmarshal(data, &manifest); err != nil {
		return project
	}
	if strings.TrimSpace(manifest.Metadata.Name) != "" {
		project.Name = manifest.Metadata.Name
	}
	project.Source = manifest.Source.Type
	project.Target = manifest.Target.Type
	return project
}

func validationSummary(report *validate.Report) BundleValidation {
	summary := BundleValidation{Status: reportStatus(report)}
	if report == nil {
		return summary
	}
	summary.Checks = len(report.Checks)
	for _, check := range report.Checks {
		switch check.Status {
		case "passed":
			summary.Passed++
		case "failed":
			summary.Failed++
		case "warning":
			summary.Warnings++
		}
	}
	return summary
}

func addSyntheticZipFile(zw *zip.Writer, prefix, rel string, modTime time.Time, data []byte, checksums map[string]string) error {
	if err := addZipFile(zw, prefix+"/"+rel, modTime, data); err != nil {
		return err
	}
	sum := sha256.Sum256(data)
	checksums[rel] = hex.EncodeToString(sum[:])
	return nil
}

func addZipFile(zw *zip.Writer, name string, modTime time.Time, data []byte) error {
	header := &zip.FileHeader{
		Name:     name,
		Method:   zip.Deflate,
		Modified: modTime,
	}
	w, err := zw.CreateHeader(header)
	if err != nil {
		return err
	}
	_, err = io.Copy(w, bytes.NewReader(data))
	return err
}

func reportStatus(report *validate.Report) string {
	if report == nil {
		return "failed"
	}
	return report.Status
}
