package export

import (
	"archive/zip"
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/RamazanKara/openexit/internal/validate"
	"github.com/RamazanKara/openexit/internal/version"
)

type Options struct {
	ProjectDir string
	Format     string
	Out        string
	Force      bool
}

func Bundle(opts Options) error {
	if opts.Format == "" {
		opts.Format = "zip"
	}
	if opts.Format != "zip" {
		return fmt.Errorf("unsupported export format %q", opts.Format)
	}
	if opts.Out == "" {
		return fmt.Errorf("--out is required")
	}
	report, err := validate.Run(opts.ProjectDir, false)
	if err != nil && !opts.Force {
		return fmt.Errorf("refusing export because validation status is %s; rerun with --force to override", reportStatus(report))
	}
	files, err := bundleFiles(opts.ProjectDir)
	if err != nil {
		return err
	}
	return writeZip(opts.ProjectDir, opts.Out, files)
}

func bundleFiles(projectDir string) ([]string, error) {
	include := map[string]bool{
		"openexit.yaml":    true,
		"inventory":        true,
		"assessment":       true,
		"generated-config": true,
		"validation":       true,
		"evidence":         true,
	}
	var files []string
	err := filepath.WalkDir(projectDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(projectDir, path)
		if err != nil || rel == "." {
			return err
		}
		top := strings.Split(filepath.ToSlash(rel), "/")[0]
		if !include[top] {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		if d.IsDir() {
			return nil
		}
		files = append(files, path)
		return nil
	})
	sort.Strings(files)
	return files, err
}

func writeZip(projectDir, out string, files []string) error {
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil && filepath.Dir(out) != "." {
		return err
	}
	f, err := os.Create(out)
	if err != nil {
		return err
	}
	defer f.Close()
	zw := zip.NewWriter(f)
	defer zw.Close()
	checksums := map[string]string{}
	prefix := "openexit-evidence"
	fixedTime := time.Date(2026, 5, 24, 0, 0, 0, 0, time.UTC)
	for _, path := range files {
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(projectDir, path)
		name := prefix + "/" + filepath.ToSlash(rel)
		if err := addZipFile(zw, name, fixedTime, data); err != nil {
			return err
		}
		sum := sha256.Sum256(data)
		checksums[filepath.ToSlash(rel)] = hex.EncodeToString(sum[:])
	}
	var checks bytes.Buffer
	keys := make([]string, 0, len(checksums))
	for path := range checksums {
		keys = append(keys, path)
	}
	sort.Strings(keys)
	for _, path := range keys {
		fmt.Fprintf(&checks, "%s  %s\n", checksums[path], path)
	}
	if err := addZipFile(zw, prefix+"/checksums.txt", fixedTime, checks.Bytes()); err != nil {
		return err
	}
	readme := fmt.Sprintf("# OpenExit Evidence Bundle\n\nGenerated by OpenExit %s.\n\nThis bundle contains local inventory, assessment, generated candidates, validation, and redacted evidence.\n", version.Version)
	return addZipFile(zw, prefix+"/README.md", fixedTime, []byte(readme))
}

func addZipFile(zw *zip.Writer, name string, modTime time.Time, data []byte) error {
	header := &zip.FileHeader{
		Name:   name,
		Method: zip.Deflate,
	}
	header.SetModTime(modTime)
	w, err := zw.CreateHeader(header)
	if err != nil {
		return err
	}
	_, err = io.Copy(w, bytes.NewReader(data))
	return err
}

func reportStatus(report *validate.Report) string {
	if report == nil {
		return "failed"
	}
	return report.Status
}
